# By: Ben Goering
# UID: Bzgoeri
# Question 1: Dictionaries and Sets

# Part A – Student Score Dictionary

In [6]:
student_scores = {
"Mia": 88,
"Noah": 76,
"Liam": 93
}

student_scores['Emma'] = 90
print(f"Noah's original score: {student_scores['Noah']}")

for student, score in student_scores.items():
    print(f'{student}: {score}')

if student_scores.get('Ava') == None:
    print("Ava: Not found")
else:
    print(student_scores.get('Ava'))


Noah's original score: 76
Mia: 88
Noah: 76
Liam: 93
Emma: 90
Ava: Not found


# Part B – Set Operations

In [17]:
python_students = {"Mia", "Noah", "Liam", "Emma"}
data_students = {"Liam", "Emma", "Olivia", "Ava"}

intersect_students = python_students & data_students
all_students = python_students | data_students

print(f"Students in both: {intersect_students}")
print(f"All students: {all_students}")

Students in both: {'Liam', 'Emma'}
All students: {'Ava', 'Liam', 'Olivia', 'Noah', 'Mia', 'Emma'}


# Question 2: Functions with Default and Keyword Arguments 

In [18]:
def calculate_total(price, quantity = 1, discount = 0.0):
    result = price * quantity
    if discount != 0:
        result = result * (1 - discount)
    return result

print(f'Single item: {calculate_total(25.0)}')
print(f'Two items: {calculate_total(25.0, 2)}')
print(f'After discount: {calculate_total(25.0, 2, .20)}')

Single item: 25.0
Two items: 50.0
After discount: 40.0


# Question 3: Generator and Exception Handling

# Part A – Generator Function

In [22]:
def multiples_of_five(limit):
    result = 0
    while(result + 5 <= limit):
        result += 5
        yield result
    return result

print(list(multiples_of_five(25)))

[5, 10, 15, 20, 25]


# Part B – Exception Handling

In [27]:
def convert_to_float(value):
    try:
        result = float (value)
    except (ValueError, TypeError):
        return "Invalid"

    return result

print(convert_to_float('18.5'))
print(convert_to_float('hello'))
print(convert_to_float('(1,2)'))

18.5
Invalid
Invalid


# Question 4: NumPy Array Operations and Indexing

In [1]:
import numpy as np

data = np.array([
[12, 18, 25, 30],
[15, 22, 28, 35],
[10, 20, 24, 32]
])

adjusted = data.copy()
adjusted = adjusted + 5

print(f'Number of dimensions: {data.ndim}')
print(f'Shape: {data.shape}\n')
print(f'Second row: {data[1]}\n')
print(f'First two rows and last two columns:\n{data[:2,-2:]}\n')
print(f'Adjusted array:\n{adjusted}\n')
print(f'Adjusted values at least 30:\n{adjusted[adjusted > 29]}')

Number of dimensions: 2
Shape: (3, 4)

Second row: [15 22 28 35]

First two rows and last two columns:
[[25 30]
 [28 35]]

Adjusted array:
[[17 23 30 35]
 [20 27 33 40]
 [15 25 29 37]]

Adjusted values at least 30:
[30 35 33 40 37]


# Question 5: Random Student Score Analysis with NumPy

In [ ]:
import random
import numpy as np

rng = np.random.default_rng(166)
scores = rng.integers(60, 101, size=(4, 2))

student_average = np.mean(scores, axis = 1)
test_average = np.mean(scores, axis = 0)
result = np.where(student_average > 74, 'Pass', 'Review')
high_score = np.max(scores)
low_score = np.min(scores)
student_average_order = np.sort(student_average)

print(f'Scores:\n{scores}')
print(f'\nStudent average: {student_average}')
print(f'Test average: {test_average}\n')
print(f'Results: {result}')
print(f'Highest score: {high_score}')
print(f'Lowest score: {low_score}')
print(f'Sorted averages: {student_average_order}')





Scores:
[[97 89]
 [62 66]
 [73 88]
 [76 69]]

Student average: [93.  64.  80.5 72.5]
Test average: [77. 78.]

Results: ['Pass' 'Review' 'Pass' 'Review']
Highest score: 97
Lowest score: 62
Sorted averages: [64.  72.5 80.5 93. ]
