By: Ben Goering
UID: bzgoeri

Question 1: Create and Modify a NumPy Array

In [12]:
import numpy as np

numbers = np.array([10,20,30,40,50])
print(numbers)
print('Shape:',numbers.shape)
print("dtype:", numbers.dtype)
double_numbers = numbers * 2
print(double_numbers)
print(numbers[1:4])

[10 20 30 40 50]
Shape: (5,)
dtype: int64
[ 20  40  60  80 100]
[20 30 40]


Problem 2: Two-Dimensional Indexing and Slicing

In [36]:
import numpy as np

numbers = np.array(
[[10, 20, 30],
[40, 50, 60],
[70, 80, 90]])

print("full array:\n", numbers)
print("second row:\n", numbers[1])
number_eighty = numbers[2,1]
print("Only 80:\n", number_eighty)
print("first 2 rows:\n",numbers[0:2])
print("Transpose:\n", numbers.T)


full array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
second row:
 [40 50 60]
Only 80:
 80
first 2 rows:
 [[10 20 30]
 [40 50 60]]
Transpose:
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


Problem 3: Boolean Indexing and np.where()

In [24]:
import numpy as np

scores = np.array([65, 78, 92, 55, 88, 70])
count_high = np.sum(scores > 69)
results = np.where(scores >= 70, 'Pass', 'Fail')

print(scores[scores > 69])
print("Number passing:", count_high)
print(results)

[78 92 88 70]
Number passing: 4
['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


Problem 4: Random Data and Basic Statistics (25 points)

In [35]:
import numpy as np

rng = np.random.default_rng(seed=12345)
data = rng.integers(50, 101, size=(3, 4))
mean = data.mean()
min = data.min()
max = data.max()
row_mean = np.round(np.mean(data, axis = 1), 1)
column_mean = np.mean(data, axis = 0)

print(data)
print(f"Mean: {mean:.2f} Minimum: {min} Maximum: {max}")
print("Row means:", row_mean)
print("Column means:", column_mean)

[[ 85  61  90  66]
 [ 60  90  82  84]
 [100  69  92  66]]
Mean: 78.75 Minimum: 60 Maximum: 100
Row means: [75.5 79.  81.8]
Column means: [81.66666667 73.33333333 88.         72.        ]
