By: Ben Goering
UID: Bzgoeri

Problem 1: Save and Load a Numpy Array

In [2]:
import numpy as np

temperatures = np.array([68, 72, 75, 70, 74])
np.save('temperatures.npy', temperatures)

loaded_temperatures = np.load('temperatures.npy')
print(loaded_temperatures)
print(loaded_temperatures.shape)
print(loaded_temperatures.dtype)

[68 72 75 70 74]
(5,)
int64


Problem 2: Element-Wise and Matrix Multiplication

In [1]:
import numpy as np

a = np.array([[2, 1],
[3, 4]])
b = np.array([[5, 2],
[1, 3]])

element_multi = a*b
matrix_multi = a@b

print(f'Element-wise multiplication:\n{element_multi}')
print(f'Element-wise result shape:{element_multi.shape}')
print(f'Matrix multiplication:\n{matrix_multi}')
print(f'Matrix result shape:{matrix_multi.shape}')



Element-wise multiplication:
[[10  2]
 [ 3 12]]
Element-wise result shape:(2, 2)
Matrix multiplication:
[[11  7]
 [19 18]]
Matrix result shape:(2, 2)


Problem 3: Selecting and Filtering a pandas Series

In [9]:
import pandas as pd

sales = pd.Series(
[120, 150, 90, 170, 140],
index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
)

tt = sales.loc[['Tuesday', 'Thursday']]
third = sales.iloc[2]
higher_sales = sales[sales >= 140]
adjusted_sales = sales + 10

print(f'Complete series:\n{sales}\n')
print(f'Tuesday and Thursday:\n{tt}\n')
print(f'Third value: {third}\n')
print(f'Sales greater than or equal to 140:\n{higher_sales}\n')
print(f'Adjusted sales:\n{adjusted_sales }')



Complete series:
Monday       120
Tuesday      150
Wednesday     90
Thursday     170
Friday       140
dtype: int64

Tuesday and Thursday:
Tuesday     150
Thursday    170
dtype: int64

Third value: 90

Sales greater than or equal to 140:
Tuesday     150
Thursday    170
Friday      140
dtype: int64

Adjusted sales:
Monday       130
Tuesday      160
Wednesday    100
Thursday     180
Friday       150
dtype: int64


Problem 4: Create and Modify a pandas DataFrame

In [15]:
data = {
"student": ["Alice", "Bob", "Carol", "David"],
"quiz": [84, 91, 78, 88],
"lab": [90, 85, 82, 94]
}
grades = pd.DataFrame(
    data,
    index = ['S1', 'S2', 'S3', 'S4']
)

student_quiz = grades[['student', 'quiz']]
updated_grades = grades.copy()
updated_grades.loc['S3', 'quiz'] = 80 
updated_grades['average'] = (updated_grades['quiz'] + updated_grades['lab'])/2
updated_grades['passed'] = updated_grades['average'] > 84

print(f'Completed DataFrame:\n {grades}\n')
print(f'Data shape: {grades.shape}\n')
print(f'Student and quiz:\n{student_quiz}\n')
print(f'Completed DataFrame:\n {updated_grades}\n')
print(f'Completed filtered DataFrame:\n {updated_grades[updated_grades['passed'] == True]}\n')

Completed DataFrame:
    student  quiz  lab
S1   Alice    84   90
S2     Bob    91   85
S3   Carol    78   82
S4   David    88   94

Data shape: (4, 3)

Student and quiz:
   student  quiz
S1   Alice    84
S2     Bob    91
S3   Carol    78
S4   David    88

Completed DataFrame:
    student  quiz  lab  average  passed
S1   Alice    84   90     87.0    True
S2     Bob    91   85     88.0    True
S3   Carol    80   82     81.0   False
S4   David    88   94     91.0    True

Completed filtered DataFrame:
    student  quiz  lab  average  passed
S1   Alice    84   90     87.0    True
S2     Bob    91   85     88.0    True
S4   David    88   94     91.0    True

